name: clone-doc
on: push

jobs:

  pushdoc:
    runs-on: ubuntu-latest
    steps:
    - run: mkdir _book && touch _book/foo.html
    - name: Checkout documentation repo
      uses: actions/checkout@v2
      with:
        repository: ${{ github.repository_owner }}/pecan-documentation
        path: pecan-documentation
        token: ${{ secrets.DOC_REPO_TOKEN }}
    - run: |
        export VERSION=${GITHUB_REF##*/}_test
        cd pecan-documentation && mkdir -p $VERSION
        git config --global user.email "pecanproj@gmail.com"
        git config --global user.name "GitHub Documentation Robot"
        rsync -a --delete ../_book/ $VERSION
        git add --all *
        git commit -m "Build book from pecan revision $GITHUB_SHA" || true
        git push -q origin master
