name: hometest
on: [push]

jobs:
  write:
    runs-on: ubuntu-latest
    steps:
    - run: echo "this is a test" >> ${HOME}/test.txt
    - run: cat ${HOME}/test.txt
    - run: echo ${HOME}
    - uses: r-lib/actions/setup-r@v1
    - run: Rscript -e 'Sys.getenv("HOME")'
