
name: use-cache
on: push

jobs:
  runs-on: ubuntu-latest
  steps:
  - run: mkdir -p the_cache
  - uses: actions/cache@v1
    with:
      key: jobonecache-${{github.ref}}-${{ github.sha }}
      path: the_cache
      restore-keys: |
          jobonecache-${{github.ref}}-
          jobonecache-
  - run: 'this is job two'
  - run: cat the_cache/msg.txt
  