name: pipe-vs-and
on: push

jobs:

  pipetest:
    runs-on: ubuntu-latest
    steps:
    - run: |
      echo there will be a pipe here once I fix the syntax
    - run: echo wtf

  andtest:
    runs-on: ubuntu-latest
    steps:
    - run: ehco this is a typo && echo this is ok
